networks:
  guardrails-network:
    driver: bridge

services:
  guardrails-service:
    image: aktosecurity/guardrails-service:a-hotfix-fix-docker-guardrails
    restart: always
    networks:
      - guardrails-network
    ports:
      - "80:8080"

    environment:
      # Kafka configuration
      # KAFKA_ENABLED: "true"
      # KAFKA_BROKER_URL: "kafka1:19092"
      # KAFKA_TOPIC: "akto.guardrails"
      # KAFKA_GROUP_ID: "guardrails-service"
      # KAFKA_BATCH_SIZE: "100"
      # KAFKA_BATCH_LINGER_SEC: "5"

      # Database abstractor service
      DATABASE_ABSTRACTOR_SERVICE_URL: "https://cyborg.akto.io"
      DATABASE_ABSTRACTOR_SERVICE_TOKEN: "${DATABASE_ABSTRACTOR_SERVICE_TOKEN}"

      # Logging
      LOG_LEVEL: "info"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
    labels:
      com.centurylinklabs.watchtower.enable: "false"

  litellm:
    image: docker.litellm.ai/berriai/litellm:main-stable
    networks:
      - guardrails-network
    ports:
      - "4000:4000"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./custom_hooks.py:/app/custom_hooks.py
    command:
      - "--config=/app/config.yaml"
      - "--port=4000"
      - "--detailed_debug"
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
      STORE_MODEL_IN_DB: "True"
    env_file:
      - .env
    depends_on:
      - db
      - guardrails-service
    healthcheck:
      test:
        - CMD-SHELL
        - python3 -c "import urllib.request; urllib.request.urlopen('http://localhost:4000/health/liveliness')"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:16
    restart: always
    container_name: litellm_db
    networks:
      - guardrails-network
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d litellm -U llmproxy" ]
      interval: 1s
      timeout: 5s
      retries: 10

  prometheus:
    image: prom/prometheus
    networks:
      - guardrails-network
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=15d"
    restart: always

volumes:
  prometheus_data:
    driver: local
  postgres_data:
    name: litellm_postgres_data
